# notebooks/Desarrollo/Agentes/mcp/azure_function/function_app.py
import azure.functions as func
import logging
from fastapi import FastAPI
from mcp.server.fastmcp import FastMCP

# Initialize logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_azure_function")

# 1. Define lifespan to manage Streamable HTTP sessions
import contextlib

@contextlib.asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize the streamable http app to make sure session_manager is instantiated
    mcp.streamable_http_app()
    # Run the session manager task group inside the lifespan
    async with mcp.session_manager.run():
        yield

# 2. Initialize FastAPI Application with Lifespan
# This acts as our main web server which Azure Functions will run via ASGI.
fastapi_app = FastAPI(
    title="MCP Server on Azure Functions",
    description="FastAPI + FastMCP server hosted serverless on Azure Functions using Streamable HTTP Transport",
    version="1.0.0",
    lifespan=lifespan
)

# 3. Create the FastMCP server with Streamable HTTP route at root of its app
# Setting host="0.0.0.0" bypasses the auto-enable check for DNS rebinding protection,
# disabling it so remote connections can be accepted safely.
mcp = FastMCP(
    "AzureFunctionsMCPServer", 
    streamable_http_path="/",
    host="0.0.0.0"
)

# In-memory storage for our demonstration tools
tasks_db = [
    {"id": 1, "task": "Learn Model Context Protocol (MCP)", "status": "In Progress"},
    {"id": 2, "task": "Create custom MCP client", "status": "Completed"},
    {"id": 3, "task": "Deploy MCP server on Azure Functions", "status": "In Progress"}
]

# 3. Define Tools on the MCP Server
@mcp.tool()
def list_tasks() -> str:
    """List all current tasks in the database.
    
    Returns:
        A text representation of the task list.
    """
    logger.info("MCP Tool 'list_tasks' called.")
    if not tasks_db:
        return "No tasks found in the database."
    
    result = "Task List:\n"
    for t in tasks_db:
        result += f"[{t['id']}] {t['task']} - Status: {t['status']}\n"
    return result

@mcp.tool()
def add_task(title: str) -> str:
    """Add a new task to the database.
    
    Args:
        title: The description/title of the task to add.
    """
    logger.info(f"MCP Tool 'add_task' called with title: {title}")
    new_id = max([t['id'] for t in tasks_db], default=0) + 1
    new_task = {"id": new_id, "task": title, "status": "Pending"}
    tasks_db.append(new_task)
    return f"Task '{title}' added successfully with ID {new_id}."

@mcp.tool()
def update_task_status(task_id: int, status: str) -> str:
    """Update the status of a specific task.
    
    Args:
        task_id: The ID of the task to update.
        status: The new status (e.g. 'Pending', 'In Progress', 'Completed').
    """
    logger.info(f"MCP Tool 'update_task_status' called for ID: {task_id} with status: {status}")
    for t in tasks_db:
        if t['id'] == task_id:
            old_status = t['status']
            t['status'] = status
            return f"Task [{task_id}] status updated from '{old_status}' to '{status}'."
    return f"Error: Task with ID {task_id} not found."

# 4. Mount FastMCP ASGI App onto the main FastAPI App
# Using streamable_http_app for the new standard Streamable HTTP transport.
fastapi_app.mount("/mcp", mcp.streamable_http_app())

# Define a root endpoint for general sanity checks
@fastapi_app.get("/")
def read_root():
    return {
        "message": "MCP Server is running on Azure Functions using Streamable HTTP!",
        "endpoints": {
            "mcp_streamable_http": "/mcp"
        }
    }

# 5. Define the ASGI Middleware to strip root_path
# This ensures that URLs generated by the SSE transport use clean, relative root paths
# (e.g. /mcp/messages instead of /api/http_app_func/mcp/messages) in Azure Functions.
class StripRootPathMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            scope["root_path"] = ""
        await self.app(scope, receive, send)

# 6. Define the Azure Function App using AsgiFunctionApp
# This binds our FastAPI application to the Azure Functions runtime.
app = func.AsgiFunctionApp(app=StripRootPathMiddleware(fastapi_app), http_auth_level=func.AuthLevel.ANONYMOUS)
